# Generated by Django 5.2.4 on 2025-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('productname', models.CharField(max_length=10)),
                ('productprice', models.FloatField()),
                ('productquantity', models.IntegerField()),
            ],
        ),
    ]
