# Generated by Django 5.2.4 on 2025-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
                ('usermobile', models.CharField(max_length=15)),
                ('addres', models.TextField()),
            ],
        ),
    ]
